name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: compilar o programa principal
        run: gcc espacopelotempo.c function_espacopelotempo.c -o espacopelotempo

      - name: executar o programa principal
        run: ./espacopelotempo 40 2 3

      - name: mostrar o conteudo do arquivo criado
        run: cat espacopelotempo.txt

      - name: compilar o arquivo de teste
        run: gcc test_espacopelotempo.c function_espacopelotempo.c -o test_espacopelotempo -lm

      - name: executar o arquivo de teste
        run: ./test_espacopelotempo
